#!/bin/bash

#Folder/File to check.
FOLDERPATH=/home/torak/Desktop; 
FOLDERSIZE=$(stat -c%s "$FOLDERPATH");

while inotifywait -r -e create,delete,move,modify $FOLDERPATH; do
	echo "Folder has changed."

	CD=734003200; #700MB in bytes
	DVD=5046586572; #4.7GB in bytes

	if [ $FOLDERSIZE -lt $CD ]
	  then
	    echo "Folder size is less than a CD size.";
	    notify-send 'Folder size is less than a CD size.' --icon=dialog-information;
	elif [ $FOLDERSIZE -gt $CD ] && [ $FOLDERSIZE -lt $DVD ]
	  then
	    echo "Folder size is greater than a CD size but less than a DVD.";
	    notify-send 'Folder size is greater than a CD size but less than a DVD.' --icon=dialog-information;
	else
	    echo "Folder size is greater than a DVD.";
	    notify-send 'Folder size is greater than a DVD.' --icon=dialog-information;
	fi

	echo ----------------------
done

